import type { NextPage } from "next";
import Head from "next/head";
import { useRef, useState } from "react";
import Intro from "../components/intro";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [query, setQuery] = useState("");
  const queryRef = useRef("");
  const searchQuery = trpc.useQuery([
    "spotify.search",
    { q: query, offset: 0, limit: 2 },
  ]);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto min-h-screen p-4">
        <Intro />
        <div className="mt-16">
          <input
            onChange={(e) => {
              queryRef.current = e.target.value;
            }}
            type="search"
            placeholder="Search for a song..."
          />
        </div>
        <button onClick={() => setQuery(queryRef.current)}>search</button>
      </main>
    </>
  );
};

export default Home;
